### PR TITLE
Adding rubocop lint style checks

### PR DESCRIPTION
**Pull request by sqorbrody**
I am trying to bring in shinken into our environment, but an struggling to get it working.  While I was at it I figured I would add some rubocop style checks.  I do not think that my rubocop adjustments are what is causing the problem.   In any case the error I get is below.   I am Chef Development Kit Version: 0.4.0.  I will try your gem set next.  Any help would be much appreciated.

rake run ....
....
 Running handlers:
       [2015-04-26T15:35:51+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2015-04-26T15:35:51+00:00] ERROR: Exception handlers complete
       [2015-04-26T15:35:51+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       Chef Client failed. 47 resources updated in 251.737740299 seconds
       [2015-04-26T15:35:51+00:00] ERROR: file[/etc/shinken/hosts/host-to-delete.cfg] (test-data::default line 9) had an error: Chef::Exceptions::UserIDNotFound: cannot determine user id for 'shinken', does the user exist on this system?
       [2015-04-26T15:35:51+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

### CODE REVIEW

**Comment by sqorbrody** [comment]
Looks like it was just a run list problem which I have now fixed.    If you want to merge the rubocop and Rakefile then it will nto break anything.

**Comment by jeffbyrnes** [comment]
@sqorbrody thanks for the additions! Some of these are somewhat opinionated, and it’s, frankly, our fault that we didn’t include a RuboCop config that demonstrates them.

I’ll fix that, and cherry-pick from here what makes sense for how we do cookbooks.

As for the runlist change; that doesn’t jibe with how I recall this cookbook should work… I’ll test that later & get back to you.

**Comment by jeffbyrnes** [comment]
@sqorbrody v1.3.0 shipped to the Supermarket, all fixed up for yah. Enjoy!

**Comment by sqorbrody** [comment]
Cool thanks

**Pull request closed without merging**
